//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmPick
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILM
    {
        public int F_ID { get; set; }
        public string F_NAME { get; set; }
        public int D_ID { get; set; }
        public int R_ID { get; set; }
        public int P_ID { get; set; }
        public int A_ID { get; set; }
        public int S_ID { get; set; }
        public int G_ID { get; set; }
    
        public virtual ACTOR ACTOR { get; set; }
        public virtual DATA DATA { get; set; }
        public virtual PRODUCER PRODUCER { get; set; }
        public virtual RATING RATING { get; set; }
        public virtual SCREENWRITER SCREENWRITER { get; set; }
        public virtual GERNE GERNE { get; set; }
    }
}
